services:
  db:
    image: postgres:alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  llm-middleware:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-middleware
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8080:8080
